threat-net/app/routes/graph.py
from flask import (
    Blueprint, flash, g, redirect, render_template, request, session, url_for
)

from app.models.DocumentDB import *


from werkzeug.datastructures import ImmutableMultiDict

import json
from pymongo import MongoClient

#TODO: add logic for when the DBs are on AWS instead of local, configure MongoClient appropriately
#see https://docs.aws.amazon.com/documentdb/latest/developerguide/connect_programmatically.html

# gets the database config from app.models.DocumentDB
client = user_graph_db

graph_db = client.graph_db #creates db if it doesn't exist already
graph_collection = graph_db.graph_collection #creates collection if it doesn't exist already

ioc_db = client.ioc_db
reg_collection = ioc_db.registery_collection
fs_collection = ioc_db.filesystem_collection

bp = Blueprint('graph', __name__, url_prefix='/graph')

@bp.route('/', methods=['GET', 'POST'])
def displayGraph():
    return render_template('graph.html')


@bp.route('/saveGraph', methods=['POST'])
def saveGraph():
  # Auto generate next id
  id = 0
  try:
    graph_list = graph_collection.find({}, {"_id": 1, "name": 1})
  except:
    print("NO DB CONNECTED. Save failed.")
    return {'Message' : "Could not save graph, no DB connected."}
  graph_dict = {}
  for graph in graph_list:
    graph_dict[graph["_id"]] = graph["name"]
  for i in graph_dict.keys():
    if graph_dict[i] == request.args.get("name"):
      id = i
  if id == 0:
    if graph_dict:
      id = max(graph_dict.keys()) + 1
  
  name = request.args.get("name")
  json_string_data = request.form.to_dict()["json_data"]

  #list of dictionaries, each dict represents a cytoscape element (node or edge)
  json_dict_data = json.loads(json_string_data) 
  
  #associate name and id before saving to DB
  graph_document = {"_id": id, "name" : name, "graph_data" : json_dict_data}

  #inserts if there is no graph with the id (i.e. the graph is new)
  try:
    graph_collection.replace_one({"_id" : id} , graph_document, upsert = True) 
  except:
    print("NO DB CONNECTED. Save failed.")
    return {'Message' : "Could not save graph, no DB connected."}

  return {'Message' : 'Sucessfully saved graph with name "{}" and ID {}'.format(name, id), 'id': id}


@bp.route('/graphList', methods=['GET'])
def getGraphList():
  try:
    graph_list = graph_collection.find({}, {"_id": 1, "name": 1}) #only return name and id
  except:
    print("NO DB CONNECTED. Could not get graph list.")
    return "ERROR: No DB connected"

  graph_dict = {}
  for graph in graph_list:
    graph_dict[graph["_id"]] = graph["name"]
  
  return json.dumps(graph_dict)


@bp.route('/loadGraph', methods=['GET'])
def loadGraph():
  dummy_data = '''[
      { data: { id: 'ioc1', label: 'IOC 1' }, position: { x: 150, y: 400 } },
      { data: { id: 'ioc2', label: 'IOC 2' }, position: { x: 250, y: 50  } },
      { data: { id: 'ioc3', label: 'IOC 3' }, position: { x: 250, y: 200 } },
      { data: { id: 'ioc4', label: 'IOC 4' }, position: { x: 350, y: 200 } },
      { data: { id: 'ioc5', label: 'IOC 5' }, position: { x: 150, y: 300 } },
      { data: { id: 'ioc6', label: 'IOC 6' }, position: { x: 250, y: 300 } },
      { data: { id: 'ioc7', label: 'IOC 7' }, position: { x: 350, y: 400 } },
      {
        data: { source: 'ioc1', target: 'ioc2', label: '1 -> 2' }
      },
      {
        data: { source: 'ioc1', target: 'ioc3', label: '1 -> 3' }
      },
      {
        data: { source: 'ioc1', target: 'ioc4', label: '1 -> 4' }
      },
      {
        data: { source: 'ioc1', target: 'ioc5', label: '1 -> 5' }
      },
      {
        data: { source: 'ioc1', target: 'ioc6', label: '1 -> 6' }
      },
      {
        data: { source: 'ioc1', target: 'ioc7', label: '1 -> 7' }
      },
      {
        data: { source: 'ioc2', target: 'ioc5', label: '2 -> 5' }
      },
      {
        data: { source: 'ioc3', target: 'ioc4', label: '3 -> 4' }
      }
  ]'''

  # if request.args.get("id") == "dummy":
  #   return dummy_data
  
  id = int(request.args.get("id"))

  try:
    graph_document = graph_collection.find_one({"_id" : id})
  except:
    print("NO DB CONNECTED. Returning hardcoded data.")
    return dummy_data

  #print(graph_document)

  if graph_document is not None:
    return json.dumps(graph_document["graph_data"])
  else:
    print("NO GRAPH WITH ID {} FOUND. Returning hardcoded data.".format(id))
    return dummy_data

threat-net/app/routes/home.py
from flask import (
    Blueprint, flash, g, redirect, render_template, request, session, url_for
)

from app.models.DocumentDB import *
from werkzeug.datastructures import ImmutableMultiDict

import json
import os

__author__ = "Kamiar Coffey"
__version__ = "1.0.1"
__email__ = "kamiar.coffey@colorado.edu"

bp = Blueprint('home', __name__, url_prefix='')

# did = request.args.get('xyz', )

python_data = {'name': 'Kamiar'} # can be anything in python including just straight JSON

@bp.route('/')
@bp.route('/home')
def home():
    return render_template('index.html', jinja_data=python_data)

@bp.route('/hello')
def hello():
    return render_template('hello.html', jinja_data=python_data)

'''Example API Style data passing'''
@bp.route('/demo', methods=['GET', 'POST'])
def dummyAPI():
    return python_data


@bp.route('/dummydata', methods=['GET', 'POST'])
def dummyData():
    return json.dumps(json.load(open('./data/dummy.json')))


@bp.route('/graphdata', methods=['GET', 'POST'])
def graphData():
	# print()
	filesystem_ioc = json.load(open('./data/FileSystem-IOC.json'))
	registry_ioc = json.load(open('./data/Registy-IOC.json'))
	# ['Dockerfile', '.gitignore', '.gcloudignore', 'README.md', 'run.py', 'app.ini', 'requirements.txt']
	return filesystem_ioc, registry_ioc

threat-net/app/templates/base.html
<!--

Author: Kamiar Coffey

- base.html is the jinja super-type doc
- this file contains a menu that is present on all child docss
-->

<!DOCTYPE html>
<html lang="en">
{% block head %}
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Threat Net {% block title %}{% endblock %}</title>
    <meta name="base layout" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
    <meta http-equiv="Content-Style-Type" content="text/css">
    <meta http-equiv="Content-Script-Type" content="text/javascript">
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="http://netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
</head>
{% endblock %}


{% block app_content %}
{% endblock %}

</html>

threat-net/app/templates/graph.html
{% extends "base.html" %}

 {% block head %}
  {{ super() }}
  <!-- <script src="https://ajax.googleapis.com/ajax/libs/d3js/5.15.0/d3.min.js"></script>
  <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet" type="text/css">
  <script src="{{url_for('static', filename='node_modules/react/umd/react.development.js')}}"></script>
  <script src="{{url_for('static', filename='node_modules/react-dom/umd/react-dom.development.js')}}"></script>
  <script src="{{url_for('static', filename='node_modules/cytoscape/dist/cytoscape.min.js')}}"></script>
  <script src="{{url_for('static', filename='node_modules/prop-types/prop-types.js')}}"></script>
  <script src="{{url_for('static', filename='node_modules/react-cytoscapejs/dist/react-cytoscape.js')}}"></script>
  <style>
    body {
      font: 14pt helvetica neue, helvetica, sans-serif;
      padding: 0;
      margin: 1em;
    }

    #root {
      display: inline-block;
    }

    #props {
      font-family: monospace;
      width: 400px;
      height: 400px;
      margin-top: 16px;
    }
  </style> -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" 
  integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" 
  crossorigin="anonymous">
 {% endblock %} <!-- endblock head -->
 
 {% block app_content %}

 <body>
  <!-- <h1>react-cytoscapejs demo</h1>

  <div id="graph"></div>
  <textarea id="props"></textarea>
  <button id="update">Render</button> -->

  <!-- Container for entire page to make use of the flexbox properties -->
    <div id="page-container">
      <div id="save-graph"></div>
      <!-- Top navigation bar -->
      <div id="nav-bar">
        <div id="logo-container"><h1 id="logo-text">ThreatNet</h1></div>
      </div>

      <!-- Container for the side pane and graph pane, so they can be arranged horizontally via flexboxes -->
      <div id="content-container">
        <!-- This is the Cytoscape graph -->
        <div id="reactEntry"></div>
      </div>


    </div>

  <script type="text/javascript" src="{{url_for('static', filename='bundle.js')}}"></script>

 </body>
 {% endblock %}

threat-net/app/templates/hello.html
<!DOCTYPE html>
<html>

<!-- Use `npm run demo` to view the demo -->

<head>
  <script src="{{url_for('static', filename='node_modules/react/umd/react.development.js')}}"></script>
  <script src="{{url_for('static', filename='node_modules/react-dom/umd/react-dom.development.js')}}"></script>
  <script src="{{url_for('static', filename='node_modules/cytoscape/dist/cytoscape.min.js')}}"></script>
  <script src="{{url_for('static', filename='node_modules/prop-types/prop-types.js')}}"></script>
  <script src="{{url_for('static', filename='node_modules/react-cytoscapejs/dist/react-cytoscape.js')}}"></script>

  <title>react-cytoscapejs demo</title>

  <style>
    body {
      font: 14pt helvetica neue, helvetica, sans-serif;
      padding: 0;
      margin: 1em;
    }

    #root {
      display: inline-block;
    }

    #props {
      font-family: monospace;
      width: 400px;
      height: 400px;
      margin-top: 16px;
    }
  </style>
</head>

<body>
  <h1>react-cytoscapejs demo</h1>

  <div id="root"></div>
  <textarea id="props"></textarea>
  <button id="update">Render</button>

  <script>
    window.addEventListener('DOMContentLoaded', function () {
      const exampleProps = {
        id: 'cy',
        className: 'foo bar',
        style: {
          'border': '1px solid #ccc',
          'width': '400px',
          'height': '400px'
        },
        global: 'cy',
        elements: [
          { data: { id: 'a', label: 'apple' }, position: { x: 0, y: 0 } },
          { data: { id: 'b', label: 'banana' }, position: { x: 100, y: 0 } },
          { data: { id: 'c', label: 'cherry' }, position: { x: 200, y: 0 } }
        ],
        layout: {
          name: 'preset'
        }
      };

      class TestComponent extends React.Component {
        constructor(props) {
          super(props);

          props.setStateRef(this.setState.bind(this));

          this.state = exampleProps;
        }

        render() {
          return React.createElement(ReactCytoscape, this.state);
        }
      }

      const textBox = document.getElementById('props');
      const btn = document.getElementById('update');

      btn.addEventListener('click', () => {
        update(JSON.parse(textBox.value));
      });

      let update;

      ReactDOM.render(
        React.createElement(TestComponent, { setStateRef: ref => update = ref }),
        document.getElementById('root')
      );

      textBox.value = JSON.stringify(exampleProps, null, 2);
    });
  </script>
</body>

</html>

threat-net/app/templates/index.html
<!--
Author: Kamiar Coffey
- index.html extends base.html
 -->


{% extends "base.html" %}

{% block head %}
  {{ super() }}
  <script src="https://ajax.googleapis.com/ajax/libs/d3js/5.15.0/d3.min.js"></script>
  <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet" type="text/css" /
{% endblock %} <!-- endblock head -->

{% block app_content %}
<h3> Variable Passing: Hello {{ jinja_data['name'] }} </h3>


<h3> API Calling: </h3>
<form>
  <div class="form-group">
    <label for="name">This Box Will Update</label>
    <input class="form-control" id="name" placeholder="World?">
  </div>

<button id='button' class="btn btn-primary">Say Hello</button>
<script type="text/javascript" src="{{url_for('static', filename='js/demoAPI.js')}}"></script>

<div class="container">
  <!-- calls the function name in home NOT the @ decorator route -->
  <iframe src="{{ url_for('home.dummyAPI') }}"></iframe>
</div>
</form>



{% endblock %}